import "./globals.css";
import { gothic } from "@/assets/fonts";

export const metadata = {
  title: "The Devil In Me || Rafael Thumaza",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-Br">
      <body className={gothic.className}>{children}</body>
    </html>
  );
}
