import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { gothic, andadaPro } from "@/assets/fonts";

export const metadata = {
  title: "The Devil In Me || Rafael Thumaza",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-Br">
      <body className={`${gothic.variable} ${andadaPro.variable}`}>
        {children}
      </body>
    </html>
  );
}
